export interface Boxers {
  id?: string;
  apodo?: string;
  img?: string;
  versus?: string;
  tandem?: boolean;
  info?: string;
}

export const boxeadores: Boxers[] = [
  {
    id: "el_mariana",
    apodo: "El Mariana",
    img: "el_mariana",
    versus: "plex",
    tandem: false,
    info: "El Mariana, cuyo nombre real es Osvaldo Palacios Flores, es un reconocido streamer, youtuber y tiktoker mexicano nacido el 23 de julio de 1998 en Matamoros, México. Inició su carrera en el mundo digital en 2017 y ha ganado popularidad principalmente por sus transmisiones de videojuegos, especialmente Call of Duty: Warzone /n Con una estatura de 1.95 metros y una presencia carismática, El Mariana ha conseguido destacarse en la comunidad digital, acumulando seguidores en diversas plataformas y colaborando con otros creadores de contenido influyentes"
  },
  {id: "plex", apodo: "Yo Soy Plex", img: "plex", versus: "el_mariana", tandem: false, info: "YoSoyPlex, cuyo nombre real es Daniel Alonso Góndez, es un destacado youtuber y streamer español nacido el 20 de septiembre de 2001 en Toro, Zamora. Con más de 13 millones de suscriptores en YouTube y 11.6 millones de seguidores en TikTok, es conocido por sus videos de Fortnite y sus ambiciosos proyectos de viaje, como dar la vuelta al mundo en 80 días. Además, ha participado en eventos de boxeo, destacando en \"La Velada del Año 4\" organizada por Ibai Llanos​ "},
  {id: "carrera", apodo: "Carreraaa", img: "carrera", versus: "agustin", tandem: false, info: "Carreraa, cuyo nombre real es Rodrigo Carrera, es un destacado streamer y creador de contenido español con más de 4.4 millones de seguidores en Twitch. Conocido por su versatilidad y sentido del humor, ha ganado popularidad gracias a sus transmisiones de videojuegos y sus imitaciones de voces en Discord. Es miembro del equipo 9Z Team y ha protagonizado momentos virales, como un incidente en el que accidentalmente incendió su cocina durante una transmisión en vivo"},
  {id: "agustin", apodo: "Agustin51", img: "agustin", versus: "carrera", tandem: false, info:"Agustin51 es un popular streamer español conocido por su contenido en videojuegos, especialmente en Brawl Stars. Con más de un millón de seguidores en Twitch, Agustin51 ha consolidado su presencia en el mundo del streaming gracias a su estilo entretenido y dinámico. Es cofundador del equipo de Esports FIVE Media Clan y ha sido nominado en los Premios ESLAND 2024 en la categoría de Streamer del Año, lo que destaca su influencia y reconocimiento en la comunidad de creadores de contenido"},
  {id: "guanyar", apodo: "Guanyar", img: "guanyar", versus: "la_cobra", tandem: false, info: "Diego Iglesias, conocido artísticamente como Guanyar, es un streamer y youtuber español que ha ganado popularidad por su contenido único y entretenido. Con tan solo 25 años, Guanyar ha logrado destacarse en la plataforma de Twitch, donde cuenta con casi medio millón de seguidores, y en YouTube, con más de 250,000 suscriptores1. Originario de Santiago de Compostela, comenzó su carrera en Barcelona y, tras la pandemia, decidió dedicarse a tiempo completo a ser creador de contenido. Es conocido por sus directos IRL (In Real Life), donde muestra su vida cotidiana y aventuras, como la serie ‘21 días sin gastar dinero’, que lo catapultó a la fama en 20231. Actualmente, reside en Madrid y colabora con el equipo de eSports Heretics, aportando sus ideas originales y su carisma natura"},
  {id: "la_cobra", apodo: "LaCobra", img: "la_cobra", versus: "guanyar", tandem: false, info:"La Cobra, cuyo nombre real es Lautaro, es un conocido streamer argentino especializado en contenido relacionado con el fútbol y otros deportes. Con más de 949,000 seguidores en Twitch, se ha destacado por sus debates y análisis futbolísticos, transmitiendo en vivo principalmente después de los partidos​ (YouTube)​​ (TwitchTracker)​. Además, La Cobra ha participado en eventos de boxeo de alto perfil, como \"La Velada del Año 4\", organizada por Ibai Llanos, donde se enfrentará a Guanyar, un evento que ha generado mucha expectación en la comunidad​ (3DJuegos)​. Su carisma y conocimiento del deporte lo han convertido en una figura prominente entre los creadores de contenido en español"},
  {id: "zeling", apodo: "zeling", img: "zeling", tandem: true, info:"Zeling, también conocida como Alicia González, es una streamer española con una destacada presencia en Twitch y YouTube. Su contenido se centra en League of Legends, y aunque ya no compite profesionalmente, sigue siendo influyente en la comunidad de jugadores y creadores de contenido. Zeling ha utilizado su plataforma para abordar temas importantes, como el acoso en línea, y su valentía la ha convertido en una figura respetada en el mundo del streaming y los videojuegos."},
  {id: "nissaxter", apodo: "nissaxter", img: "nissaxter", tandem: true, info: "Nissaxter, también conocida como Cristina, es una streamer española que ha ganado notoriedad en Twitch gracias a su contenido centrado en League of Legends. Nissaxter lleva casi tres años triunfando con sus divertidos directos, donde juega al LoL y reacciona a todas sus jugadas con pasión. Originaria de Barcelona, comenzó su carrera en Twitch en 2017, inicialmente transmitiendo partidas de Overwatch y Fortnite. Sin embargo, fue su deseo de subir de rango en el League of Legends y su divertida frustración al perder partidas lo que la hizo viral en 2022. Desde entonces, es creadora de contenido oficial del equipo de eSports Giants y ha participado en diversas series de streamers, incluyendo la primera edición de El último en pie de Ibai Llanos12. Con más de 770,000 seguidores en Twitch y 168,000 suscriptores en YouTube, Nissaxter es una figura influyente en el mundo del streaming y los videojuegos. Su progresivo crecimiento se ha visto impulsado por su impetuosidad y su irascibilidad, lo que la llevó a estar nominada a “Mejor Enfado de 2021” en los premios ESLAND2. ¡Una verdadera reina del rageo en Twitch España!"},
  {id: "alana", apodo: "alana", img: "alana", tandem: true, info: "Alana Flores, también conocida como Alana Scarlett o Alana La Rana, es una streamer mexicana que ha ganado notoriedad en Twitch y otras redes sociales. Nacida en Monterrey el 15 de diciembre de 2000, Alana comenzó a llamar la atención en las redes sociales a los 19 años. Durante la pandemia, se lanzó a hacer directos en Twitch, lo que la posicionó rápidamente como una de las streamers más nuevas e interesantes de México. Actualmente, cuenta con 470,000 seguidores en Twitch, 1 millón de seguidores en Instagram y casi dos millones en TikTok. Su contenido abarca desde el fitness hasta los videojuegos. Además, Alana es una de las creadoras de contenido oficiales de 19esports y comparte una relación con BarcaGamer, con quien ahora es copresidenta del equipo Ranizas F.C., un proyecto que los emociona debido a su pasión compartida por el fútbol"},
  {id: "ama", apodo: "AmaBlitz", img: "ama", tandem: true, info:"Amablitz, también conocida como Amairani Garza Alonso, es una destacada figura en el mundo del streaming y las redes sociales. Nacida el 1 de marzo de 1995 en Monterrey, México, Amablitz ha logrado un impresionante seguimiento gracias a su carisma, talento y diversidad de contenido. Antes de sumergirse en el mundo digital, Amablitz se especializó en diseño industrial, una carrera que refleja su creatividad y atención al detalle. Su educación en diseño no solo ha influenciado su estilo personal y profesional, sino que también le ha proporcionado una base sólida para su carrera como creadora de contenido. Amablitz comenzó su carrera en el streaming en 2014, cuando abrió su canal de YouTube para compartir su pasión por los videojuegos. Desde entonces, ha expandido su presencia a plataformas como Twitch, Instagram, Facebook y TikTok, donde transmite una variedad de contenidos que van desde videojuegos hasta blogs y experiencias personales. A lo largo de los años, Amablitz ha acumulado más de 683,000 suscriptores en YouTube y más de 6 millones de seguidores en Instagram. Uno de sus TikToks más populares, en el que aparece bailando con un traje de animadora, ha ganado más de 9 millones de visitas. Además, ha demostrado tener talento como modelo, capturando la atención de sus seguidores con su habilidad para posar frente a la cámara. Como influencer, Amablitz ha colaborado con diversas marcas y personalidades, ampliando su alcance y solidificando su estatus como una figura prominente en el entretenimiento digital. Su hermana, Ari Gameplays, también es una reconocida streamer y juntas han formado un dúo dinámico en el mundo del streaming12. Además, recientemente, Amablitz ha sido anunciada como participante en la Velada del Año 4, un evento boxístico de streamers organizado por Ibai Llanos, donde será entrenada por el boxeador profesional mexicano Jhonny González"},
  {id: "viruzz", apodo: "ByViruzz", img: "viruzz", versus: "shelao", tandem: false, info:"Víctor Mélida Cambra, más conocido como ByViruzz, es un influencer y streamer español que ha ganado popularidad desde su inicio en las redes sociales en 20151. Nacido el 1 de mayo de 1992 en Zaragoza, Víctor comenzó su carrera en el mundo digital compartiendo contenido sobre videojuegos como Clash of Clans y Clash Royale en plataformas como YouTube y Twitch1. Además de su pasión por los videojuegos, Víctor tiene un trasfondo deportivo como jugador profesional de balonmano y ha incursionado en el boxeo, participando en eventos como ‘La velada del año’ organizada por Ibai Llanos1. Con más de 5,78 millones de suscriptores en su canal principal de YouTube y una presencia significativa en Twitch e Instagram, ByViruzz se ha establecido como un creador de contenido versátil y carismático"},
  {id: "shelao", apodo: "Shelao", img: "shelao", versus: "viruzz", tandem: false, info:"Shelao, cuyo nombre real es Cristóbal Álvarez, es un conocido streamer y modelo chileno. Ganó fama internacional tras su participación en el reality chileno Doble Tentación y su victoria en el concurso de belleza masculina Mister Real Universe en 20151. En Twitch, se destaca por transmitir contenido variado, incluyendo juegos como Minecraft y League of Legends, y cuenta con una audiencia considerable2. Además, Shelao ha entrenado en boxeo durante varios años y ha capturado la atención de sus seguidores por su técnica de lucha, lo que le ha llevado a participar en el evento de boxeo ‘La Velada del Año 3’ organizado por Ibai Llanos3. Su éxito como creador de contenido en Latinoamérica se está expandiendo también en España"},
];
